import { Item, Warehouse, Supplier, Customer, PurchaseOrder, SalesOrder, StockLedgerEntry } from '../types';

export const initialItems: Item[] = [
  {
    name: 'ITEM-0001',
    item_name: 'Cold Rolled Steel Coil',
    sku: 'CR-COIL-01',
    item_group: 'Raw Materials',
    stock_uom: 'Kg',
    valuation_rate: 85,
    standard_selling_rate: 120,
    current_stock: 4500,
    reorder_level: 5000,
    reorder_qty: 2000,
    description: 'High-quality steel coil for stamping and structural components.',
  },
  {
    name: 'ITEM-0002',
    item_name: 'Aluminum Ingot 99.7%',
    sku: 'AL-INGT-997',
    item_group: 'Raw Materials',
    stock_uom: 'Kg',
    valuation_rate: 170,
    standard_selling_rate: 240,
    current_stock: 1800,
    reorder_level: 1000,
    reorder_qty: 1000,
    description: 'Pure aluminum ingots for casting and alloying.',
  },
  {
    name: 'ITEM-0003',
    item_name: 'M12 Hex Bolt (High Tensile)',
    sku: 'HTB-M12-50',
    item_group: 'Hardware & Fasteners',
    stock_uom: 'Nos',
    valuation_rate: 8,
    standard_selling_rate: 15,
    current_stock: 12000,
    reorder_level: 15000,
    reorder_qty: 5000,
    description: 'Grade 8.8 medium carbon steel high tensile fasteners.',
  },
  {
    name: 'ITEM-0004',
    item_name: 'Lithium-Ion Battery Cell 21700',
    sku: 'LI-CELL-217',
    item_group: 'Electronics',
    stock_uom: 'Nos',
    valuation_rate: 32,
    standard_selling_rate: 45,
    current_stock: 350,
    reorder_level: 2000,
    reorder_qty: 3000,
    description: 'High-capacity cylindrical battery cell for pack assembly.',
  },
  {
    name: 'ITEM-0005',
    item_name: 'Printed Circuit Board Assembly (v2.1)',
    sku: 'PCBA-V2.1',
    item_group: 'Sub-Assemblies',
    stock_uom: 'Nos',
    valuation_rate: 110,
    standard_selling_rate: 180,
    current_stock: 95,
    reorder_level: 150,
    reorder_qty: 200,
    description: 'Main control board with pre-soldered active and passive components.',
  },
];

export const initialWarehouses: Warehouse[] = [
  {
    name: 'Raw Materials - SCMS',
    warehouse_name: 'Raw Materials',
    type: 'Store',
    current_capacity: 6300, // weight-based capacity (approx 4500 steel + 1800 aluminum)
    max_capacity: 10000,
  },
  {
    name: 'Finished Goods - SCMS',
    warehouse_name: 'Finished Goods',
    type: 'Store',
    current_capacity: 95, // quantity-based
    max_capacity: 2000,
  },
  {
    name: 'Transit Hub - SCMS',
    warehouse_name: 'Transit Hub',
    type: 'Transit',
    current_capacity: 0,
    max_capacity: 1500,
  },
  {
    name: 'Quality Inspection - SCMS',
    warehouse_name: 'Quality Inspection',
    type: 'Inspection',
    current_capacity: 12000, // Bolt quantity
    max_capacity: 30000,
  },
];

export const initialSuppliers: Supplier[] = [
  {
    name: 'Apex Metal Works',
    supplier_group: 'Raw Material Supplier',
    status: 'Active',
    contact_email: 'sales@apexmetalworks.com',
    contact_phone: '+1-555-0198',
    address: '404 Foundry Lane, Industrial District, Sector 4',
  },
  {
    name: 'LithiumTech Solutions',
    supplier_group: 'Electronics Vendor',
    status: 'Active',
    contact_email: 'support@lithiumtech.co',
    contact_phone: '+82-2-555-1234',
    address: '77 Techno Boulevard, Guro-gu, Seoul',
  },
  {
    name: 'Precision Fasteners Ltd',
    supplier_group: 'Hardware Components',
    status: 'Active',
    contact_email: 'orders@prefasteners.com',
    contact_phone: '+1-555-0142',
    address: '12 Threading Way, Manufacturing Park, Ohio',
  },
];

export const initialCustomers: Customer[] = [
  {
    name: 'Tesla Motors Corp',
    customer_group: 'Automotive OEM',
    status: 'Active',
    email: 'scm-inbound@tesla.com',
    phone: '+1-555-0800',
    address: '3500 Deer Creek Road, Palo Alto, CA',
  },
  {
    name: 'Siemens Industrial',
    customer_group: 'Engineering & Controls',
    status: 'Active',
    email: 'procure@siemens.com',
    phone: '+49-89-636-00',
    address: 'Werner-von-Siemens-Straße 1, Munich',
  },
  {
    name: 'EcoEnergy Systems',
    customer_group: 'Renewable Energy',
    status: 'Active',
    email: 'inventory@ecoenergy.net',
    phone: '+1-555-0999',
    address: '90 Solar Grid Ave, Austin, TX',
  },
];

export const initialPurchaseOrders: PurchaseOrder[] = [
  {
    name: 'PO-2026-00001',
    supplier: 'Apex Metal Works',
    transaction_date: '2026-06-15',
    schedule_date: '2026-06-25',
    status: 'Received',
    items: [
      {
        item_code: 'ITEM-0001',
        item_name: 'Cold Rolled Steel Coil',
        qty: 2000,
        received_qty: 2000,
        rate: 85,
        amount: 170000,
        uom: 'Kg',
      },
    ],
    grand_total: 170000,
    total_qty: 2000,
  },
  {
    name: 'PO-2026-00002',
    supplier: 'LithiumTech Solutions',
    transaction_date: '2026-07-02',
    schedule_date: '2026-07-15',
    status: 'Submitted',
    items: [
      {
        item_code: 'ITEM-0004',
        item_name: 'Lithium-Ion Battery Cell 21700',
        qty: 3000,
        received_qty: 0,
        rate: 32,
        amount: 96000,
        uom: 'Nos',
      },
    ],
    grand_total: 96000,
    total_qty: 3000,
  },
  {
    name: 'PO-2026-00003',
    supplier: 'Precision Fasteners Ltd',
    transaction_date: '2026-07-05',
    schedule_date: '2026-07-12',
    status: 'Draft',
    items: [
      {
        item_code: 'ITEM-0003',
        item_name: 'M12 Hex Bolt (High Tensile)',
        qty: 5000,
        received_qty: 0,
        rate: 8,
        amount: 40000,
        uom: 'Nos',
      },
    ],
    grand_total: 40000,
    total_qty: 5000,
  },
];

export const initialSalesOrders: SalesOrder[] = [
  {
    name: 'SO-2026-00001',
    customer: 'Tesla Motors Corp',
    transaction_date: '2026-06-20',
    delivery_date: '2026-06-28',
    status: 'Shipped',
    items: [
      {
        item_code: 'ITEM-0005',
        item_name: 'Printed Circuit Board Assembly (v2.1)',
        qty: 50,
        delivered_qty: 50,
        rate: 180,
        amount: 9000,
        uom: 'Nos',
      },
    ],
    grand_total: 9000,
    total_qty: 50,
  },
  {
    name: 'SO-2026-00002',
    customer: 'Siemens Industrial',
    transaction_date: '2026-07-04',
    delivery_date: '2026-07-10',
    status: 'Submitted',
    items: [
      {
        item_code: 'ITEM-0002',
        item_name: 'Aluminum Ingot 99.7%',
        qty: 200,
        delivered_qty: 0,
        rate: 240,
        amount: 48000,
        uom: 'Kg',
      },
    ],
    grand_total: 48000,
    total_qty: 200,
  },
];

export const initialStockLedger: StockLedgerEntry[] = [
  {
    name: 'SLE-00001',
    item_code: 'ITEM-0001',
    warehouse: 'Raw Materials - SCMS',
    actual_qty: 2500,
    valuation_rate: 85,
    voucher_type: 'Stock Entry',
    voucher_no: 'STE-2026-00001',
    posting_date: '2026-01-10',
    posting_time: '10:00:00',
  },
  {
    name: 'SLE-00002',
    item_code: 'ITEM-0002',
    warehouse: 'Raw Materials - SCMS',
    actual_qty: 2000,
    valuation_rate: 170,
    voucher_type: 'Stock Entry',
    voucher_no: 'STE-2026-00001',
    posting_date: '2026-01-10',
    posting_time: '10:00:00',
  },
  {
    name: 'SLE-00003',
    item_code: 'ITEM-0003',
    warehouse: 'Quality Inspection - SCMS',
    actual_qty: 12000,
    valuation_rate: 8,
    voucher_type: 'Stock Entry',
    voucher_no: 'STE-2026-00001',
    posting_date: '2026-01-10',
    posting_time: '10:00:00',
  },
  {
    name: 'SLE-00004',
    item_code: 'ITEM-0004',
    warehouse: 'Raw Materials - SCMS',
    actual_qty: 350,
    valuation_rate: 32,
    voucher_type: 'Stock Entry',
    voucher_no: 'STE-2026-00001',
    posting_date: '2026-01-10',
    posting_time: '10:00:00',
  },
  {
    name: 'SLE-00005',
    item_code: 'ITEM-0005',
    warehouse: 'Finished Goods - SCMS',
    actual_qty: 145,
    valuation_rate: 110,
    voucher_type: 'Stock Entry',
    voucher_no: 'STE-2026-00001',
    posting_date: '2026-01-10',
    posting_time: '10:00:00',
  },
  // Inward from PO-2026-00001
  {
    name: 'SLE-00006',
    item_code: 'ITEM-0001',
    warehouse: 'Raw Materials - SCMS',
    actual_qty: 2000,
    valuation_rate: 85,
    voucher_type: 'Purchase Receipt',
    voucher_no: 'PO-2026-00001',
    posting_date: '2026-06-25',
    posting_time: '14:30:22',
  },
  // Outward from SO-2026-00001
  {
    name: 'SLE-00007',
    item_code: 'ITEM-0005',
    warehouse: 'Finished Goods - SCMS',
    actual_qty: -50,
    valuation_rate: 110,
    voucher_type: 'Delivery Note',
    voucher_no: 'SO-2026-00001',
    posting_date: '2026-06-28',
    posting_time: '09:15:00',
  },
];
